//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int funcionarioid { get; set; }
        public string nome { get; set; }
        public string departamento { get; set; }
        public string cargo { get; set; }
        public string email { get; set; }
    }
}
